# Generated by Django 5.0.2 on 2024-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debtor_id', models.IntegerField()),
                ('claimer_id', models.IntegerField()),
                ('debtor_data', models.JSONField()),
                ('claimer_data', models.JSONField()),
                ('status', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
