# Generated by Django 5.0.2 on 2024-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_id', models.IntegerField(null=True)),
                ('claimer_id', models.IntegerField(null=True)),
                ('debtor_data', models.JSONField(null=True)),
                ('claimer_data', models.JSONField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
