# Generated by Django 5.0.2 on 2024-08-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_alter_comparisonresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonresult',
            name='claimer_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='claimer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='debtor_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='debtor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
