# Generated by Django 5.0.2 on 2024-11-02 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_column', models.CharField(max_length=100)),
                ('columns_file1', models.JSONField()),
                ('columns_file2', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_file_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file1', to='upload.excelfile')),
                ('excel_file_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file2', to='upload.excelfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
