# Generated by Django 5.0.2 on 2024-11-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_column', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_file1', to='upload.excelfile')),
                ('file2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_file2', to='upload.excelfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_file1', models.CharField(max_length=255)),
                ('column_file2', models.CharField(max_length=255)),
                ('combined_column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_selections', to='matching.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_column_value', models.CharField(max_length=255)),
                ('data_file1', models.JSONField()),
                ('data_file2', models.JSONField()),
                ('status', models.CharField(choices=[('Match', 'Match'), ('Mismatch', 'Mismatch')], max_length=50)),
                ('description', models.TextField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='matching.comparison')),
            ],
        ),
    ]
