# Generated by Django 5.0.2 on 2024-10-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0008_rename_diznew_claimer_dlznew'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debtor_columns', models.JSONField()),
                ('claimer_columns', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_column_value', models.CharField(max_length=255)),
                ('matched_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer_history', to='upload.excelfile')),
                ('debtor_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_history', to='upload.excelfile')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.matchingpreset')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_column_value', models.CharField(max_length=255)),
                ('matched_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer_matches', to='upload.excelfile')),
                ('debtor_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_matches', to='upload.excelfile')),
            ],
        ),
    ]
