# Generated by Django 5.0.2 on 2024-03-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelBase',
            new_name='DebtorExcelBase',
        ),
    ]
