# Generated by Django 5.0.2 on 2024-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='side_by_side_data_file1',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='side_by_side_data_file2',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
