# Generated by Django 4.2.5 on 2024-11-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_excelfile_file'),
        ('matching', '0002_comparisonresult_side_by_side_data_file1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debtor_columns', models.JSONField()),
                ('claimer_columns', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_column_value', models.CharField(max_length=255)),
                ('matched_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer_matches', to='upload.excelfile')),
                ('debtor_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_matches', to='upload.excelfile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_column_value', models.CharField(max_length=255)),
                ('matched_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer_history', to='upload.excelfile')),
                ('debtor_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_history', to='upload.excelfile')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.matchingpreset')),
            ],
        ),
    ]
