# Generated by Django 5.0.2 on 2024-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_claimerexcelbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorexcelbase',
            name='prosthetic_fee',
            field=models.FloatField(null=True),
        ),
    ]
