# Generated by Django 5.0.2 on 2024-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_debtorexcelbase_prosthetic_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimerexcelbase',
            name='prosthetic_fee',
            field=models.FloatField(null=True),
        ),
    ]
