# Generated by Django 5.0.2 on 2024-03-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_claimerexcelbase_prosthetic_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('preset_data', models.JSONField()),
            ],
        ),
    ]
