# Generated by Django 5.0.2 on 2024-04-28 12:25

import django.db.models.deletion
import matching.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_claimerexcelbase_no_alter_debtorexcelbase_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debtor_file', models.FilePathField(match='.xlsx', path=matching.models.debtor_upload_path, recursive=True)),
                ('claimer_file', models.FilePathField(match='.xlsx', path=matching.models.claimer_upload_path, recursive=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='HospMain',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='HospSub',
            new_name='BegHd',
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='claim_catg',
            new_name='ClaimAcc',
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='claim_folname',
            new_name='DizNew',
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='AdjRw',
            new_name='Ext',
        ),
        migrations.RenameField(
            model_name='claimerexcelbase',
            old_name='Lab_fee',
            new_name='Herg',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='AN',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='AuthenCode',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='CID',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='No',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='Pdx',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='Pttype',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='X_Ray_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='admit_date',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='amount_paid_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='amount_tobe_paid_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='bloodcomponent_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='claim_catg_code',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='claim_folname_code',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='debt_left_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='dental_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='doctor_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='drug_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='equipment_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='expense_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='left_date',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='medical_supplie_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='not_insure_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='nursing_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='other_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='othertharapy_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='p_chart_status',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='physicaltharapy_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='procedure_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='prosthetic_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='room_food_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='special_inspection_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='takehome_drug_fee',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='claimerexcelbase',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='debtorexcelbase',
            name='AN',
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='Ep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='HDrate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='HdMode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='NetTotal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='Payers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='SessNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='Stat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='bill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='common_column',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='importdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='importstaff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimerexcelbase',
            name='line',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debtorexcelbase',
            name='common_column',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimerexcelbase',
            name='HN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claimerexcelbase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='matching.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('debtor_mapping', models.JSONField(null=True)),
                ('claimer_mapping', models.JSONField(null=True)),
                ('admin_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_preset', to='matching.excelfile')),
                ('ceo_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_preset', to='matching.excelfile')),
                ('claimer_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claimer_preset', to='matching.excelfile')),
                ('debtor_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_preset', to='matching.excelfile')),
            ],
        ),
    ]
