# Generated by Django 5.0.2 on 2024-04-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_customuser_excelfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='admit_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='left_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
