# Generated by Django 5.0.2 on 2024-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_alter_debtorexcelbase_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='admit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='left_date',
            field=models.DateField(null=True),
        ),
    ]
