# Generated by Django 5.0.2 on 2024-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_alter_debtorexcelbase_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='AuthenCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debtorexcelbase',
            name='p_chart_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
