# Generated by Django 5.0.2 on 2024-10-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_excelfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='sugery',
            new_name='surgery',
        ),
    ]
