# Generated by Django 4.2.6 on 2024-02-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='claimer_excel',
        ),
        migrations.DeleteModel(
            name='debtor_excel',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
