# Generated by Django 5.0.2 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_claimer_amount_alter_claimer_beghd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimer',
            name='HN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='VN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='importStaff',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='importdate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='location',
            field=models.CharField(choices=[('debtor', 'Debtor'), ('claimer', 'Claimer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='AccCode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='AuthenCode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='CID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='HN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='HospSub',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='National',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='Pttype_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='VN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='location',
            field=models.CharField(choices=[('debtor', 'Debtor'), ('claimer', 'Claimer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='vstdate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='vsttime',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='location',
            field=models.CharField(choices=[('debtor', 'Debtor'), ('claimer', 'Claimer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=30),
        ),
    ]
