# Generated by Django 5.0.2 on 2024-10-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_claimer_amount_alter_claimer_beghd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='HospMain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='HospSub',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='National',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='location',
            field=models.CharField(choices=[('debtor', 'Debtor'), ('claimer', 'Claimer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=30),
        ),
    ]
