# Generated by Django 5.0.2 on 2024-10-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_debtor_hospmain_alter_debtor_hospsub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimer',
            old_name='DizNew',
            new_name='DlzNew',
        ),
    ]
